### ISSUE TITLE
OFFSET exceeds maximum of 10000

### ISSUE THREAD

**Issue by jacobtonndorf** [redis/redis-om-spring#105]
Hello,

when I do something like this:
```
Pageable pageRequest = PageRequest.of(3, 5000);
repository.findByVariableBetween(0, 1000000, pageRequest);
 ```
 I get the following error:
 
 ```
 redis.clients.jedis.exceptions.JedisDataException: OFFSET exceeds maximum of 10000
	at redis.clients.jedis.Protocol.processError(Protocol.java:142)
	at redis.clients.jedis.Protocol.process(Protocol.java:176)
	at redis.clients.jedis.Protocol.read(Protocol.java:230)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:352)
	at redis.clients.jedis.Connection.getUnflushedObjectMultiBulkReply(Connection.java:314)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:319)
	at io.redisearch.client.Client.search(Client.java:394)
	at io.redisearch.client.Client.search(Client.java:374)
	at com.redis.om.spring.ops.search.SearchOperationsImpl.search(SearchOperationsImpl.java:45)
	at com.redis.om.spring.repository.query.RediSearchQuery.executeQuery(RediSearchQuery.java:298)
	at com.redis.om.spring.repository.query.RediSearchQuery.execute(RediSearchQuery.java:251)
 ```
 
 Is this a limitation of jedis or a limitation of this specific query, as I can do this without any problems:
 
```
Pageable pageable = PageRequest.of(3, 5000);
repository.findAll(pageable);
```

**Comment by bsbodden** [comment]
You are hitting the server configuration pre-set limit of 10,000. I think it might be something you can change with an `FT.CONFIG` but I haven't tried myself yet.
