### ISSUE TITLE
TTL not used

### ISSUE THREAD

**Issue by Paure42** [redis/redis-om-spring#128]
Hi,

I'm the using the TTL on a Redis Document like that `@Document(value = "XXXXX", timeToLive = 60 * 60 * 24 * 7)`, it works for some keys but after a while the new keys have a TTL equals to -1.

**Comment by bsbodden** [comment]
Thanks for reporting. I'll check it out and try to reproduce it. Any other scenario info you might have is appreciated.

**Comment by Paure42** [comment]
Thank you.

I'm using `redis/redis-stack:edge`

Here is my pom: 
![image](https://user-images.githubusercontent.com/56505105/200360196-ba75807c-b3f7-4bfc-9c06-23883a6a8a1a.png)

**Comment by bsbodden** [comment]
Can you try with `0.6.2` to confirm that it is still present?

**Comment by Paure42** [comment]
The bug is still there.
I have to drop the index and restart the application to resolve it, but when I do that the bug appears on another index. I wonder if it's because the restart of an application that the new keys have a bad ttl ?

**Comment by bsbodden** [comment]
With TTLs is pretty hard to debug, I don't have any tests where I simulate the application restarting so that might be the key

**Comment by bsbodden** [comment]
See #129

**Comment by bsbodden** [comment]
Should be resolved in https://s01.oss.sonatype.org/content/repositories/snapshots/com/redis/om/redis-om-spring/0.6.3-SNAPSHOT/

Could please try it?

**Comment by Paure42** [comment]
After several tests I think the bug is fixed with this version ! Thank you !

However, I think there is another bug with the TTL but I may be wrong, when a query looks for an element of a key, in my case a hash compute with some elements, that has been erased by the time to live, there is a null pointer exception thrown:

java.lang.NullPointerException
	at com.redis.om.spring.repository.query.RediSearchQuery.executeQuery(RediSearchQuery.java:344)
	at com.redis.om.spring.repository.query.RediSearchQuery.execute(RediSearchQuery.java:267)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:159)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy174.findByHash(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy174.findByHash(Unknown Source)

**Comment by bsbodden** [comment]
@Paure42 can you open another issue for that one? Thanks!
