### ISSUE TITLE
StackOverflowError if redis document has an indexed Set<Integer> field

### ISSUE THREAD

**Issue by praks84** [redis/redis-om-spring#137]
Hi

Using Spring boot 2.7.6 and redis-om-spring 0.6.3

I have a data model with a field of type Set<Integer>
If I annotate my data model with @Document and that field with @Indexed, then I get java.lang.StackOverflowError at application startup and the application fails to start

	at com.redis.om.spring.RediSearchIndexer.getNestedField(RediSearchIndexer.java:430)
	at com.redis.om.spring.RediSearchIndexer.getNestedField(RediSearchIndexer.java:473)

**Comment by bsbodden** [comment]
@praks84 can you post a the full stack trace and the java file for the model and repo. Thanks!
