### ISSUE TITLE
findOneByName error

### ISSUE THREAD

**Issue by axinger** [redis/redis-om-spring#145]
pom
```
<dependency>
  <groupId>com.redis.om</groupId>
  <artifactId>redis-om-spring</artifactId>
  <version>0.6.3</version>
</dependency>
```

redis
```
 docker run -d --name redis-stack -p 6376:6379 -p 8001:8001 redis/redis-stack:edge
```

```
@Data
@NoArgsConstructor
@RequiredArgsConstructor(staticName = "of")
@AllArgsConstructor(access = AccessLevel.PROTECTED)
@Document
public class Company {
    @Id
    private String id;

    @NonNull
    @Searchable
    private String name;

    @Indexed
    private Set<String> tags = new HashSet<String>();

    @NonNull
    private String url;

    @NonNull
    @Indexed
    private Point location;

    @NonNull
    @Indexed
    private Integer numberOfEmployees;

    @NonNull
    @Indexed
    private Integer yearFounded;

    private boolean publiclyListed;

    // audit fields

    @CreatedDate
    private Date createdDate;

    @LastModifiedDate
    private Date lastModifiedDate;
}
```

```
public interface CompanyRepository extends RedisDocumentRepository<Company, String> {
  // find one by property
  Optional<Company> findOneByName(String name);

  Iterable<Company> findAllByName(String name);
}
```

```
  @Test
    void test2() {
        Optional<Company> redis = companyRepo.findOneByName("Redis");
        System.out.println("redis = " + redis);

        Iterable<Company> redis1 = companyRepo.findAllByName("Redis");
        System.out.println("redis1 = " + redis1);
    }
```

error

```
redis.clients.jedis.exceptions.JedisDataException: xxx.CompanyIdx: no such index

	at redis.clients.jedis.Protocol.processError(Protocol.java:139)
	at redis.clients.jedis.Protocol.process(Protocol.java:173)
	at redis.clients.jedis.Protocol.read(Protocol.java:227)
```

**Comment by bsbodden** [comment]
Your code is fine, it's likely your test that is not working. Here the same code working on a standalone app https://github.com/bsbodden/issue-145
