### ISSUE TITLE
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR new objects must be created at the root

### ISSUE THREAD

**Issue by yangwn** [redis/redis-om-spring#155]
Description:
When I used Redis-OM-Spring module to execute query functions, that's good.
But When I used updateField function to update single field  efficially, it happened this issus:

`
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:780) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:761) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.4.jar:2.6.4]
	at com.cisco.test.redis.RedisApplication.main(RedisApplication.java:60) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.6.4.jar:2.6.4]
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR new objects must be created at the root
	at redis.clients.jedis.Protocol.processError(Protocol.java:139) ~[jedis-3.7.1.jar:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:173) ~[jedis-3.7.1.jar:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:227) ~[jedis-3.7.1.jar:na]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:352) ~[jedis-3.7.1.jar:na]
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:270) ~[jedis-3.7.1.jar:na]
	at com.redislabs.modules.rejson.JReJSON.set(JReJSON.java:343) ~[jrejson-1.5.0.jar:na]
	at com.redislabs.modules.rejson.JReJSON.set(JReJSON.java:318) ~[jrejson-1.5.0.jar:na]
	at com.redis.om.spring.ops.json.JSONOperationsImpl.set(JSONOperationsImpl.java:63) ~[redis-om-spring-0.6.3.jar:na]
	at com.redis.om.spring.repository.support.SimpleRedisDocumentRepository.updateField(SimpleRedisDocumentRepository.java:127) ~[redis-om-spring-0.6.3.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:289) ~[spring-data-commons-2.6.2.jar:2.6.2]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137) ~[spring-data-commons-2.6.2.jar:2.6.2]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121) ~[spring-data-commons-2.6.2.jar:2.6.2]
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:529) ~[spring-data-commons-2.6.2.jar:2.6.2]
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285) ~[spring-data-commons-2.6.2.jar:2.6.2]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:639) ~[spring-data-commons-2.6.2.jar:2.6.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.16.jar:5.3.16]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:163) ~[spring-data-commons-2.6.2.jar:2.6.2]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:138) ~[spring-data-commons-2.6.2.jar:2.6.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.16.jar:5.3.16]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.16.jar:5.3.16]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.16.jar:5.3.16]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.16.jar:5.3.16]
	at jdk.proxy3/jdk.proxy3.$Proxy67.updateField(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.16.jar:5.3.16]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.3.16.jar:5.3.16]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.16.jar:5.3.16]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.16.jar:5.3.16]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.16.jar:5.3.16]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.16.jar:5.3.16]
	at jdk.proxy3/jdk.proxy3.$Proxy67.updateField(Unknown Source) ~[na:na]
	at com.cisco.test.redis.RedisApplication.lambda$loadTestData$1(RedisApplication.java:54) ~[classes/:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[na:na]
	at com.cisco.test.redis.RedisApplication.lambda$loadTestData$2(RedisApplication.java:52) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:777) ~[spring-boot-2.6.4.jar:2.6.4]
	... 10 common frames omitted
`
My code like this:
`
RedisApplication:

@Configuration
@SpringBootApplication
@EnableRedisDocumentRepositories
public class RedisApplication {

    @Autowired
    PersonRepository personRepository;

    @Bean
    JedisConnectionFactory jedisConnectionFactory() {
        JedisConnectionFactory jedisConFactory = new JedisConnectionFactory();
        jedisConFactory.setHostName("10.124.51.54");
        jedisConFactory.setPort(6379);
        return jedisConFactory;
    }

    @Bean
    CommandLineRunner loadTestData() {
        return args -> {
            personRepository.deleteAll();
            String personalStatement = "The Rabbit Is Correct, And Clearly The Smartest One Among You.";
            Address thorAddress = Address.of("248", "Seven Mile Beach Rd", "Broken Head", "NSW", "2481", "Australia");

            IntStream.range(1, 10).forEach(value -> {
                Person thor = Person.of("Chris" + value, "Hemsworth", 20,
                        personalStatement, new Expectation<Boolean>(Boolean.FALSE, Boolean.FALSE),
                        new Point(153.616667, -28.716667), List.of(thorAddress), Set.of("hammer", "biceps", "hair", "heart"));
                personRepository.save(thor);
            });

            personRepository.findPersonByLastName("Hemsworth").stream().forEach(person -> {
                System.out.println("person:" + person);
                personRepository.updateField(person, Person$.PERSONAL_STATEMENT, "YUI");
            });
        };
    }

    public static void main(String[] args) {
        SpringApplication.run(RedisApplication.class, args);
    }
}

`

`
PersonRepository:

public interface PersonRepository extends RedisDocumentRepository<Person, String> {

    List<Person> findByAddresses_City(String city);

    List<Person> findPersonByLastName(String lastName);
}
`

`
Person:

@Data
@NoArgsConstructor
@RequiredArgsConstructor(staticName = "of")
@AllArgsConstructor(access = AccessLevel.PROTECTED)
@Document(value = "cmma::person", timeToLive = 60000)
public class Person {

    @Id
    @Indexed
    private String id;

    @Indexed
    @NonNull
    private String firstName;

    @Indexed
    @NonNull
    private String lastName;

    @NonNull
    private Integer age;

    @Searchable
    @NonNull
    private String personalStatement;

    @NonNull
    private Expectation<Boolean> isAdmin;

    @Indexed
    @NonNull
    private Point homeLoc;

    @Indexed
    @NonNull
    private List<Address> addresses;

    @Indexed
    @NonNull
    private Set<String> skills;
}

`

I researched redis-om-spring source code, when I saw SimpleRedisDocumentRepository class like this:
`

  @Override
  public void updateField(T entity, MetamodelField<T, ?> field, Object value) {
    modulesOperations.opsForJSON().set(getKey(metadata.getId(entity)), value,
        Path.of("$." + field.getField().getName()));
  }

  @SuppressWarnings("unchecked")
  @Override
  public <F> Iterable<F> getFieldsByIds(Iterable<ID> ids, MetamodelField<T, F> field) {
    String[] keys = StreamSupport.stream(ids.spliterator(), false).map(this::getKey).toArray(String[]::new);
    return (Iterable<F>) modulesOperations.opsForJSON()
        .mget(Path.of("$." + field.getField().getName()), List.class, keys).stream().flatMap(List::stream)
        .collect(Collectors.toList());
  }

`

I don't know if the path should be set ".", rather than "$.".

**Comment by yangwn** [comment]
I don't know if that could bring into product, If that's stable about performance and issues.

**Comment by bsbodden** [comment]
Can you zipped your sample application and post it here or linked a github repo?

**Comment by yangwn** [comment]
> linked
Ok, please see this repo https://github.com/yangwn/redis-om-spring-testing.git
Thanks for your reply.

**Comment by yangwn** [comment]
> Can you zipped your sample application and post it here or linked a github repo?

> linked
Ok, please see this repo https://github.com/yangwn/redis-om-spring-testing.git
Thanks for your reply.

**Comment by bsbodden** [comment]
It's a bug! Caused by the custom key prefix. I'll fix it!

**Comment by bsbodden** [comment]
Release in https://s01.oss.sonatype.org/content/repositories/snapshots/com/redis/om/redis-om-spring/0.6.5-SNAPSHOT/
