### ISSUE TITLE
saveAll does not support an Id with type Long

### ISSUE THREAD

**Issue by rjdkolb** [redis/redis-om-spring#172]
Based on the example roms-documents, if I change the @Id to a Long instead of a String, I get a ClassCastException error.

**versions:**
redis-om-spring version 0.6.4.
Redis version 6.2.6-v2 (docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:6.2.6-v2)

```
public class Company {
  @Id
  private Long id;

Company redis1 = Company.of(CompanyName.of("Redis"), "wwwabccom", new Point(-122.066540, 37.377690), 526, 2011, Set.of(CompanyMeta.of("Redis", 100, Set.of("RedisTag"))));
Company redis2 = Company.of(CompanyName.of("Redis"), "wwwxyzcom", new Point(-122.066540, 37.377690), 526, 2011, Set.of(CompanyMeta.of("Redis", 100, Set.of("RedisTag"))));
```

This works

```
companyRepo.save(redis1);
companyRepo.save(redis2);
```

This does not :

`companyRepo.saveAll(List.of(redis1, redis2 ));`

Error is

```
Caused by: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.String (java.lang.Long and java.lang.String are in module java.base of loader 'bootstrap')
	at com.redis.om.spring.repository.support.SimpleRedisDocumentRepository.saveAll(SimpleRedisDocumentRepository.java:168) ~[redis-om-spring-0.6.4.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
```

**Comment by GeoffreyBourboin** [comment]
Same problem here !

**Comment by rjdkolb** [comment]
I added a [PR](https://github.com/redis/redis-om-spring/pull/177) unfortunately it is not backed by a unit test.

**Comment by bsbodden** [comment]
@rjdkolb I wonder with the call to `saveAll` in `NonStandardDocumentSearchTest` did not throw the exception?

**Comment by bsbodden** [comment]
@rjdkolb @GeoffreyBourboin and I assume you made changes to the Repo interface too to be `public interface CompanyRepository extends RedisDocumentRepository<Company, Long>`

**Comment by GeoffreyBourboin** [comment]
@bsbodden When will you merge into 2.7 and when will you make another release ?

**Comment by bsbodden** [comment]
> @bsbodden When will you merge into 2.7 and when will you make another release ?

Merging into the 2.7 branch now and will release a SNAPSHOT of both branches later today (02/07)
