### ISSUE TITLE
Use Query Limit app property across all dynamic queries

### ISSUE THREAD

**Issue by prutheus** [redis/redis-om-spring#286]
I have a data model like this:

```java
@Data
@Builder
@RedisHash
public class Job {
    @Id
    private String id;
    private String profession;
    private String city;
    private String title;
    private String description;
    private String url;
    @Indexed
    private Boolean valid;
    @Indexed
    @Builder.Default
    private Long timestamp = Instant.now().toEpochMilli();
}
```

And a `JobRepository` as following:

```java
@Repository
public interface JobRepository extends RedisEnhancedRepository<Job, String> {
    List<Job> getAllByValidIsAndTimestampIsBetween(Boolean valid, Long fromTimestamp, Long toTimestamp);
}
```

However, when calling `getAllByValidIsAndTimestampIsBetween` I get a exception:

```
redis.clients.jedis.exceptions.JedisDataException: No such field
	at redis.clients.jedis.Protocol.processError(Protocol.java:96) ~[jedis-4.3.0.jar:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:137) ~[jedis-4.3.0.jar:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:192) ~[jedis-4.3.0.jar:na]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:316) ~[jedis-4.3.0.jar:na]
	at redis.clients.jedis.Connection.getOne(Connection.java:298) ~[jedis-4.3.0.jar:na]
	at redis.clients.jedis.Connection.executeCommand(Connection.java:123) ~[jedis-4.3.0.jar:na]
	at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:24) ~[jedis-4.3.0.jar:na]
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:167) ~[jedis-4.3.0.jar:na]
	at redis.clients.jedis.UnifiedJedis.ftTagVals(UnifiedJedis.java:3571) ~[jedis-4.3.0.jar:na]
	at com.redis.om.spring.ops.search.SearchOperationsImpl.tagVals(SearchOperationsImpl.java:190) ~[redis-om-spring-0.8.4.jar:na]
	at com.redis.om.spring.repository.query.RedisEnhancedQuery.executeFtTagVals(RedisEnhancedQuery.java:561) ~[redis-om-spring-0.8.4.jar:na]
	at com.redis.om.spring.repository.query.RedisEnhancedQuery.execute(RedisEnhancedQuery.java:350) ~[redis-om-spring-0.8.4.jar:na]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136) ~[spring-data-commons-3.0.3.jar:3.0.3]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120) ~[spring-data-commons-3.0.3.jar:3.0.3]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164) ~[spring-data-commons-3.0.3.jar:3.0.3]
...
```

However, when checking the `monitor` profiler of my Redis instance, I see that this command is executed:

```
"FT.TAGVALS" "XXXXXXXXX.JobIdx" "byValidIsAndTimestampIsBetween"
```

which makes no sense ... any idea what went wrong?

**Comment by bsbodden** [comment]
Try `findAllByValidAndTimestampBetween` perhaps - we reserve `getAll` for retrieving all possible values in a TAG field. Remember this is not exactly JPA. Below I collected the queries against `@Document` entities that we have in the tests that are known to work. 

```java
Optional<MyDoc> findByTitle(String title);
Page<MyDoc> findAllByTitleStartingWith(String title, Pageable pageable);
List<MyDoc> findAllByTitleEndingWith(String title);
Iterable<MyDoc> findByTag(Set<String> tags);
Iterable<MyDoc> findByLocationNear(Point point, Distance distance);
Iterable<MyDoc> findByLocation2Near(Point point, Distance distance);
Iterable<MyDoc> findByaNumber(Integer anotherNumber);
Optional<NiCompany> findFirstByName(String name);
Optional<SKU> findOneBySkuNumber(String skuNumber);
List<SKU> findAllBySkuNumberIn(Set<String> skuNumbers);
List<SKU> findAllBySkuNameIn(Set<String> dearSkuNumbers);
Optional<User> findFirstByName(String name);
Optional<WithAlias> findFirstByNumber(Integer number);

// Numeric range queries:
// FT.SEARCH permits "@construction_value:[42000,42000]"
// find by numeric property
// Result: Every document that has a construction value of exactly 42000, so tst:permit:1.
Iterable<Permit> findByConstructionValue(long value);

// Performing a text search on a specific field:
// FT.SEARCH permits "@building_type:detached" 
Iterable<Permit> findByBuildingType(String buildingType);

// Performing a tag search
// FT.SEARCH permits "@city:{Lisbon}"
Iterable<Permit> findByAddress_City(String city);

// search documents that have one of multiple tags (OR condition)
// FT.SEARCH permits "@work_type:{construction|design}"
Iterable<Permit> findByWorkType(Set<String> workTypes);

// Search documents that have all the tags (AND condition):
// FT.SEARCH permits "@work_type:{construction} @work_type:{design}"
Iterable<Permit> findByWorkTypeContainingAll(Set<String> workTypes);

// Performing a combined search on two fields (AND):
// FT.SEARCH permits "@building_type:house @description:new"
Iterable<Permit> findByBuildingTypeAndDescription(String buildingType, String description);

// Performing a combined search on two fields (OR):
// FT.SEARCH permits "(@city:{Lagos})|(@description:detached)"
Iterable<Permit> findByAddress_CityOrDescription(String buildingType, String description);

// Performing a nested tag search
// FT.SEARCH permits "(@value:{M})"
Iterable<Permit> findByAttrList_Value(String value);

// Performing a multi-level nested tag search
// FT.SEARCH permits "(@skuNo:{ABC})"
Iterable<Permit> findByAttrList_orderList_skuNo(String skuNo);

// performing a combined search on two fields (or):
// FT.SEARCH permits "(@skuNo:{GHJ})|(@description:New)"
Iterable<Permit> findByAttrList_orderList_skuNoOrDescription(String skuNo, String description);

//
// OM Specific
//

SearchResult findByBody(String text);

@Query("@title:$prefix*")
Page<MyDoc> customFindAllByTitleStartingWith(@Param("prefix") String prefix, Pageable pageable);

@Query(value="@title:$prefix*", returnFields={"title", "aNumber"}, limit = 12, offset = 1, sortBy = "title")
SearchResult customFindAllByTitleStartingWithReturnFieldsAndLimit(@Param("prefix") String prefix);
  
/**
 * <pre>
 * > FT.TAGVALS idx tags
 * </pre>
 */
Iterable<String> getAllTag();


@Query("(@name:{$name}) (@address:{$address}) (@addressComplement:{$addressComp})")
Iterable<User2> findUser( //
    @Param("name") String name, //
    @Param("address") String strAdd, //
    @Param("addressComp") String strAddComp //
);

// Performing a text search on all text fields:
// FT.SEARCH permits "veranda"
// Result: Documents inside which the word 'veranda' occurs, so tst:permit:1.
Iterable<Permit> search(String text);

// A fuzzy text search on all text fields:
// FT.SEARCH permits "%%haus%%" 
// Result: Documents with words similar to 'haus' (tst:permit:1 and tst:permit:3). The number of % indicates the allowed Levenshtein distance (later more about it). So the query would also match on 'house' because 'haus' and 'house' have a distance of two.

// Perform search with paging and sorting parameters
Page<Permit> search(String text, Pageable pageable);
```

**Comment by prutheus** [comment]
with `findAllBy...` it works fine, but it just returns max `10` items ... I have specified:

```
redis:
  om:
    spring:
      repository:
        query:
          limit: 1000000
```

so I thought it will return max `1000000` items per query, am I wrong?

**Comment by prutheus** [comment]
@bsbodden maybe there is a fix release for this possible soon?

**Comment by prutheus** [comment]
Okay thanks! Looking forward to the release 🎉

**Comment by bsbodden** [comment]
Likely next week, adding more tests this week.

**Comment by prutheus** [comment]
@bsbodden my query as stated above:
`List<Job> getAllByValidIsAndTimestampIsBetween(Boolean valid, Long fromTimestamp, Long toTimestamp);` still just returns 10 items ... not 100k, as I have set the limit to in my `application.yml` config file.

**Comment by prutheus** [comment]
@bsbodden please find this repo (https://github.com/prutheus/redis-om-spring-test) to reproduce the issue

**Comment by bsbodden** [comment]
> @bsbodden please find this repo (https://github.com/prutheus/redis-om-spring-test) to reproduce the issue

I guess I totally missed that you were working with Hashes and not JSON, I've testing the JSON repos, I just submitted a PR that addresses the Hash repository queries.

**Comment by prutheus** [comment]
Awesome, looking forward for a release soon 🤩

**Comment by abhi-121** [comment]
@bsbodden Tried setting up the query limit to 100k, but still its fetching a max of 10k entities only (given redis has more than 10k records). Any other configs need to add or am I missing something here ?
```
entityStream.of(Entity.class)
                .dialect(2)..collect(Collectors.toList());

redis.om.spring.repository.query.limit=100000
```

**Comment by aempinheiro** [comment]
> [@bsbodden](https://github.com/bsbodden) Tried setting up the query limit to 100k, but still its fetching a max of 10k entities only (given redis has more than 10k records). Any other configs need to add or am I missing something here ?
> 
> ```
> entityStream.of(Entity.class)
>                 .dialect(2)..collect(Collectors.toList());
> 
> redis.om.spring.repository.query.limit=100000
> ```
> 
> using redis-om-spring.version=0.9.8

No reply to this @bsbodden? the issue seems to persist using the entity stream is this intentional? if yes is it documented?
