### ISSUE TITLE
No attribute named messageListenerContainerRef found

### ISSUE THREAD

**Issue by yj18523574287** [redis/redis-om-spring#328]
i use redission， But this error is reported when starting
java.lang.IllegalArgumentException: No attribute named messageListenerContainerRef found
	at org.springframework.data.repository.config.AnnotationRepositoryConfigurationSource.getAttribute(AnnotationRepositoryConfigurationSource.java:277)
	at org.springframework.data.repository.config.AnnotationRepositoryConfigurationSource.getAttribute(AnnotationRepositoryConfigurationSource.java:266)
	at org.springframework.data.redis.repository.configuration.RedisRepositoryConfigurationExtension.createRedisKeyValueAdapter(RedisRepositoryConfigurationExtension.java:152)
	at org.springframework.data.redis.repository.configuration.RedisRepositoryConfigurationExtension.lambda$registerBeansForRoot$4(RedisRepositoryConfigurationExtension.java:111)
	at org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport.registerIfNotAlreadyRegistered(RepositoryConfigurationExtensionSupport.java:231)
	at org.springframework.data.redis.repository.configuration.RedisRepositoryConfigurationExtension.registerBeansForRoot(RedisRepositoryConfigurationExtension.java:111)
	at org.springframework.data.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn(RepositoryConfigurationDelegate.java:136)
	at com.redis.om.spring.repository.configuration.RedisEnhancedRepositoriesRegistrar.registerBeanDefinitions(RedisEnhancedRepositoriesRegistrar.java:83)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:396)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:395)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:157)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:343)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:748)
	at org.springframework.context.support.AbstractApplicationContext.__refresh(AbstractApplicationContext.java:564)
	at org.springframework.context.support.AbstractApplicationContext.jrLockAndRefresh(AbstractApplicationContext.java:41002)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:42008)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at com.supply.mall.SupplyMallApplication.main(SupplyMallApplication.java:20)
2023-08-11 16:33:43 [Thread-33] WARN  c.a.nacos.common.notify.NotifyCenter
 - [NotifyCenter] Start destroying Publisher
2023-08-11 16:33:43 [Thread-33] WARN  c.a.nacos.common.notify.NotifyCenter
 - [NotifyCenter] Destruction of the end
2023-08-11 16:33:43 [Thread-28] WARN  c.a.n.c.http.HttpClientBeanHolder
 - [HttpClientBeanHolder] Start destroying common HttpClient
2023-08-11 16:33:43 [Thread-28] WARN  c.a.n.c.http.HttpClientBeanHolder
 - [HttpClientBeanHolder] Destruction of the end
Disconnected from the target VM, address: '127.0.0.1:59757', transport: 'socket'

Process finished with exit code 1

**Comment by bsbodden** [comment]
You might want to report this to the redisson or Spring Data Redis repositories. This is unrelated to this library.
