### ISSUE TITLE
JedisDataException: ERR unknown command 'JSON.SET'

### ISSUE THREAD

**Issue by greamrod** [redis/redis-om-spring#50]
```java
redis.clients.jedis.exceptions.JedisDataException: ERR unknown command 'JSON.SET', with args beginning with: 'com.macro.mall.tiny.domain.Product:0' '.' '{"id":0,"productSn":"string","name":"string","subTitle":"string","brandName":"string"' 
	at redis.clients.jedis.Protocol.processError(Protocol.java:139) ~[jedis-3.7.1.jar:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:173) ~[jedis-3.7.1.jar:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:227) ~[jedis-3.7.1.jar:na]
```

pom.xml
```xml
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.2</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>


<dependencies>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-web</artifactId>
    </dependency>

    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-test</artifactId>
        <scope>test</scope>
    </dependency>

    <dependency>
        <groupId>io.springfox</groupId>
        <artifactId>springfox-boot-starter</artifactId>
        <version>3.0.0</version>
    </dependency>

    <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <optional>true</optional>
    </dependency>

    <dependency>
        <groupId>com.redis.om</groupId>
        <artifactId>redis-om-spring</artifactId>
        <version>0.5.0</version>
    </dependency>
</dependencies>
```
Javebean
```java
@Data
@EqualsAndHashCode(callSuper = false)
@Document(language = "chinese")
public class Product {
    @Id
    private Long id;
    @Indexed
    private String productSn;
    @Searchable
    private String name;
    @Searchable
    private String subTitle;
    @Indexed
    private String brandName;
    @Indexed
    private Integer price;
    @Indexed
    private Integer count;
}
```

ProductController .java
```java
@RestController
@RequestMapping("/product")
public class ProductController {
    @Autowired
    private ProductRepository productRepository;


    @PostMapping("/import")
    public CommonResult importList() {
        productRepository.deleteAll();
        List<Product> productList = LocalJsonUtil.getListFromJson("json/products.json", Product.class);
        for (Product product : productList) {
            productRepository.save(product);
        }
        return CommonResult.success(null);
    }

    @PostMapping("/create")
    public CommonResult create(@RequestBody Product entity) {
        productRepository.save(entity);
        return CommonResult.success(null);
    }

    @PostMapping("/delete/{id}")
    public CommonResult delete(@PathVariable Long id) {
        productRepository.deleteById(id);
        return CommonResult.success(null);
    }

    @GetMapping("/detail/{id}")
    public CommonResult<Product> detail(@PathVariable Long id) {
        Optional<Product> result = productRepository.findById(id);
        return CommonResult.success(result.orElse(null));
    }

    @GetMapping("/page")
    public CommonResult<List<Product>> page(@RequestParam(defaultValue = "1") Integer pageNum,
                                            @RequestParam(defaultValue = "5") Integer pageSize) {
        Pageable pageable = PageRequest.of(pageNum - 1, pageSize);
        Page<Product> pageResult = productRepository.findAll(pageable);
        return CommonResult.success(pageResult.getContent());
    }

    @GetMapping("/getByBrandName")
    public CommonResult<List<Product>> getByBrandName(String brandName) {
        List<Product> resultList = productRepository.findByBrandName(brandName);
        return CommonResult.success(resultList);
    }

    @GetMapping("/search")
    public CommonResult<List<Product>> search(String keyword) {
        List<Product> resultList = productRepository.findByNameOrSubTitle(keyword, keyword);
        return CommonResult.success(resultList);
    }
}
```

**Comment by bsbodden** [comment]
@greamrod can you check your Redis installation by launching the Redis CLI and typing:

```bash
127.0.0.1:6379> module list
1) 1) "name"
   2) "timeseries"
   3) "ver"
   4) (integer) 10607
2) 1) "name"
   2) "graph"
   3) "ver"
   4) (integer) 20808
3) 1) "name"
   2) "search"
   3) "ver"
   4) (integer) 20400
4) 1) "name"
   2) "ReJSON"
   3) "ver"
   4) (integer) 20007
5) 1) "name"
   2) "bf"
   3) "ver"
   4) (integer) 20213
```

That will list the modules installed, it is likely that you don't have the JSON module installed. Download Redis Stack if that is the case (it comes pre-installed with the JSON and Search modules).

You can find it here ==> https://redis.io/docs/stack/get-started/install/
