### ISSUE TITLE
QueryUtils is not escaping the space character

### ISSUE THREAD

**Issue by fabrizio-cannizzaro** [redis/redis-om-spring#512]
QueryUtils is not escaping the space character
 When a parameter containing a space (" ") is passed this exception is raised
In this test the parameter was "In Camera"

Suppressed: redis.clients.jedis.exceptions.JedisDataException: Syntax error at offset 63 near Camera
		at redis.clients.jedis.Protocol.processError(Protocol.java:105)
		at redis.clients.jedis.Protocol.process(Protocol.java:162)
		at redis.clients.jedis.Protocol.read(Protocol.java:221)
		at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:351)
		at redis.clients.jedis.Connection.getOne(Connection.java:333)
		at redis.clients.jedis.Connection.executeCommand(Connection.java:138)
		at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:24)
		at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:244)
		at redis.clients.jedis.UnifiedJedis.ftSearch(UnifiedJedis.java:3705)
		at com.redis.om.spring.ops.search.SearchOperationsImpl.search(SearchOperationsImpl.java:46)
		at com.redis.om.spring.search.stream.SearchStreamImpl.executeQuery(SearchStreamImpl.java:527)
		at com.redis.om.spring.search.stream.SearchStreamImpl.resolveStream(SearchStreamImpl.java:577)
		at com.redis.om.spring.search.stream.SearchStreamImpl.close(SearchStreamImpl.java:446)
		at ec.ep.pericles.imv.bidao.impl.MeetingDocumentDaoImpl.search(MeetingDocumentDaoImpl.java:31)
		... 185 common frames omitted

public static final Set<Character> TAG_ESCAPE_CHARS = Set.of(',', '.', '<', '>', '{', '}', '[', ']', '"', '\'', ':', ';', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '-', '+', '=', '~', '|', '/');

**Comment by bsbodden** [comment]
@fabrizio-cannizzaro sorry for the late reply, to escape spaces also use the form `tring escape(String text, boolean querying)` with `querying` set to `true`
