### ISSUE TITLE
Bug: search Command using '*' cannot be serialised 

### ISSUE THREAD

**Issue by ally-jarrett** [redis/redis-om-spring#80]
Repository implementation: 

`Page<Movie> search(String searchCriteria, Pageable pageable);`

When you perform a query to return all results i.e. '*' this causes a stack trace from redis-om e.g. 

`searchCriteria = "*"`

this translates into the valid RediSearch query: `"FT.SEARCH" "io.redis.model.MovieIdx" "*" "LIMIT" "0" "20"`

however redis-om throws:

`java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.9.jar:na]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[gson-2.8.9.jar:na]`

This is because the RediSearch results set is not just an Array but instead returns: 

```
> FT.SEARCH "io.redis.model.MovieIdx" "*" "LIMIT" "0" "20"
1) "9899"
2) "io.redis.model.Movie:1234"
3) 1) <JSON_Array>
```

redis-om should be able to account for queries such as these.

**Comment by ally-jarrett** [comment]
I've tested with the latest RedisStack impl and this issue is fixed. I noticed discrepancies in the responses RedisSearch was returning.
